const titles = [
    "Smart Personal Health Tracker",
    "Automated Job Application System",
    "Remote Work Collaboration Tool",
    "Blockchain-based Educational Credentials Verification",
    "AI-driven Tutoring System",
    "Elderly Care Monitoring System",
    "Crowdsourced Urban Traffic Data Collection",
    "Mobile Application for Mental Wellness",
    "Smart Waste Recycling Management",
    "AR-based Interior Design Tool",
    "Food Waste Reduction App",
    "Personalized Fitness Coaching App",
    "Digital Marketplace for Freelancers",
    "Home Energy Consumption Monitoring",
    "Interactive Language Learning Application",
    "Smart Agriculture Management Tool",
    "Online Community for Skill Sharing",
    "Telemedicine Platform for Remote Consultations",
    "Blockchain-based Voting System",
    "Mobile Application for Local Business Promotions",
    "AI-Powered Travel Recommendation Engine",
    "Online Mental Health Support Group",
    "Smart Campus Navigation App",
    "Virtual Reality Fitness Experiences",
    "Automated Social Media Content Planner",
    "IoT-Based Smart Water Quality Monitoring",
    "Mobile Payment Solution for Local Markets",
    "Data Analytics Platform for Nonprofits",
    "AI-driven E-learning System",
    "Blockchain-based Supply Chain Transparency",
    "IoT-enabled Smart Home Security System",
    "Mobile App for Emergency Services",
    "Digital Content Management System for Schools",
    "Smart Public Transportation Management",
    "AI-driven Health Diagnostics Tool",
    "Online Platform for Local Artisans",
    "Automated Travel Expense Tracking App",
    "Mobile Application for Pet Care Management",
    "Smart Grid Management System",
    "Blockchain-based Intellectual Property Rights Management",
    "Mobile App for Fitness Challenges",
    "Telecommuting Optimization Tool",
    "AI-powered Personal Finance Advisor",
    "Digital Marketplace for Eco-Friendly Products",
    "Interactive Community Engagement Platform",
    "Smart Traffic Management System",
    "AI-based Resume Builder and Job Matcher",
    "Online Platform for Creative Collaboration",
    "Digital Health Records Management System",
    "Virtual Reality Tour Guide for Historic Sites",
    "IoT-based Environmental Monitoring System",
    "Mobile App for Local Food Delivery",
    "Automated Plant Care System",
    "Blockchain-based Crowdfunding Platform",
    "AI-driven Predictive Maintenance System",
    "Digital Personal Organizer with AI",
    "Remote Learning Assessment Tool",
    "Mobile Application for Volunteer Coordination",
    "Smart Inventory Management System",
    "Online Coding Bootcamp Platform",
    "AI-Powered Content Generation Tool",
    "Crowdsourced Disaster Recovery Platform",
    "Smart Building Management System",
    "Mobile App for Daily Habit Tracking",
    "Blockchain-based Real Estate Transactions",
    "AI-driven Social Media Sentiment Analysis",
    "Digital Asset Management System",
    "Mobile App for Skill Development Workshops",
    "Smart Fleet Management System",
    "Virtual Reality Rehabilitation Therapy",
    "Online Platform for Student Mentorship",
    "IoT-enabled Smart Farming Solutions",
    "Automated Water Conservation System",
    "Mobile App for Community News Sharing",
    "AI-powered Language Translation Tool",
    "Digital Toolkit for Remote Workers",
    "Mobile Application for Public Health Awareness",
    "Smart Waste Sorting System",
    "Blockchain-based Supply Chain Management",
    "IoT-based Traffic Light Control System",
    "Mobile App for Real-time Market Prices",
    "Automated Home Cleaning System",
    "AI-driven Predictive Analytics for Businesses",
    "Online Tutoring Platform with AI Support",
    "Digital Event Planning Application",
    "Smart Health and Fitness Application",
    "Mobile App for Product Reviews and Recommendations",
    "Blockchain-based Voting System for Student Elections",
    "AI-driven Fraud Detection System",
    "Web-Based Disaster Preparedness Platform",
    "Smart Water Distribution Management",
    "Digital Personal Health Journal",
    "Online Marketplace for Handmade Products",
    "AI-driven Academic Research Assistant",
    "Mobile Application for Community Gardening",
    "Smart Retail Experience Using AR",
    "Blockchain-based Donation Tracking System",
    "Virtual Reality Educational Experiences",
    "Online Music Collaboration Platform",
    "IoT-based Home Energy Management System",
    "Automated Public Feedback Collection System",
    "AI-Powered Career Counseling Tool",
    "Mobile App for Sustainable Living Practices",
    "Digital Voting System for Organizations",
    "Smart Parking Management System",
    "Blockchain-based Contract Management System",
    "AI-driven Marketing Insights Platform",
    "Online Fitness Class Scheduling Tool"
];

document.getElementById("generate-btn").addEventListener("click", () => {
    const randomIndex = Math.floor(Math.random() * titles.length);
    const randomTitle = titles[randomIndex];
    document.getElementById("title").innerText = randomTitle;
});
